In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

#Importing the dataset and selecting the columns

In [18]:
dataset = pd.read_csv('datathon_train.csv')
dataset.drop(dataset.columns[[0,5,6,7,9,10,11,12,13,14,16,17,18,19]], axis = 1, inplace = True)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [19]:
X

array([['M', 'Y', 'N', ..., 0, 0.631220343, 5],
       ['M', 'Y', 'Y', ..., 0, 0.392746019, 3],
       ['M', 'Y', 'Y', ..., 0, 0.222536676, 2],
       ...,
       ['F', 'Y', 'Y', ..., 1, 0.826586671, 1],
       ['M', 'Y', 'Y', ..., 0, 0.103523331, 5],
       ['M', 'Y', 'Y', ..., 1, 0.435078756, 5]], dtype=object)

#Encoding the categorical variables

In [20]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
le = LabelEncoder()
#gender
X[:, 0] = le.fit_transform(X[:, 2])
#s11
X[:, 1] = le.fit_transform(X[:, 2])
#s12
X[:, 2] = le.fit_transform(X[:, 2])
#s58
X[:, 5] = le.fit_transform(X[:, 2])

In [21]:
X

array([[0, 0, 0, ..., 0, 0.631220343, 5],
       [1, 1, 1, ..., 0, 0.392746019, 3],
       [1, 1, 1, ..., 0, 0.222536676, 2],
       ...,
       [1, 1, 1, ..., 1, 0.826586671, 1],
       [1, 1, 1, ..., 0, 0.103523331, 5],
       [1, 1, 1, ..., 1, 0.435078756, 5]], dtype=object)

In [22]:
'''from sklearn.impute import SimpleImputer 
imputer=SimpleImputer(missing_values=np.NAN,strategy='mean',fill_value=None,verbose=0,copy=True)
imputer=imputer.fit(X[:,:]) 
X[:,:]=imputer.transform(X[:,:])'''

"from sklearn.impute import SimpleImputer \nimputer=SimpleImputer(missing_values=np.NAN,strategy='mean',fill_value=None,verbose=0,copy=True)\nimputer=imputer.fit(X[:,:]) \nX[:,:]=imputer.transform(X[:,:])"

#Training the dataset

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

#Feature Scaling

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Building the ann

In [25]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
ann.compile(optimizer='adam' , loss='binary_crossentropy' , metrics=['accuracy'] )

#TRaining the ann

In [26]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
620/620 [==============================] - 2s 2ms/step - loss: 0.4484 - accuracy: 0.8330
Epoch 2/100
620/620 [==============================] - 1s 2ms/step - loss: 0.3848 - accuracy: 0.8440
Epoch 3/100
620/620 [==============================] - 1s 2ms/step - loss: 0.3726 - accuracy: 0.8545
Epoch 4/100
620/620 [==============================] - 1s 2ms/step - loss: 0.3684 - accuracy: 0.8549
Epoch 5/100
620/620 [==============================] - 1s 2ms/step - loss: 0.3661 - accuracy: 0.8556
Epoch 6/100
620/620 [==============================] - 1s 2ms/step - loss: 0.3642 - accuracy: 0.8561
Epoch 7/100
620/620 [==============================] - 1s 2ms/step - loss: 0.3630 - accuracy: 0.8564
Epoch 8/100
620/620 [==============================] - 1s 2ms/step - loss: 0.3621 - accuracy: 0.8575
Epoch 9/100
620/620 [==============================] - 1s 2ms/step - loss: 0.3615 - accuracy: 0.8572
Epoch 10/100
620/620 [==============================] - 1s 2ms/step - loss: 0.3609 - accura

#Predicting test-set results

In [27]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


#Making the confusion matrix

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[6943  145]
 [1076  333]]


0.8563022243144639

#Testing the model with the test dataset

In [39]:
test_dataset = pd.read_csv('datathon_test.csv')
submission_dataset = pd.read_csv('submission.csv')

#Loading test dataset

In [40]:
test_dataset.drop(test_dataset.columns[[0,5,6,7,9,10,11,12,13,14,16,17,18,19]], axis = 1, inplace = True)
X = test_dataset.iloc[:, :].values
#y = test_dataset.iloc[:, -1].values
X

array([['M', 'Y', 'Y', ..., 0, 0.439270435, 2],
       ['M', 'Y', 'Y', ..., 0, 0.084334211, 4],
       ['M', 'Y', 'N', ..., 0, 0.984209575, 0],
       ...,
       ['M', 'N', 'Y', ..., 0, 0.571894753, 3],
       ['M', 'N', 'Y', ..., 0, 0.655693348, 6],
       ['M', 'Y', 'Y', ..., 0, 0.785251224, 2]], dtype=object)

#Encoding the categorical values

In [41]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
le = LabelEncoder()
#gender
X[:, 0] = le.fit_transform(X[:, 2])
#s11
X[:, 1] = le.fit_transform(X[:, 2])
#s12
X[:, 2] = le.fit_transform(X[:, 2])
#s58
X[:, 5] = le.fit_transform(X[:, 2])

#Feature scaling

In [43]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

#Predicting results

In [56]:
y_pred = ann.predict(X)
#print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))
y_pred

array([[0.3963246 ],
       [0.09917587],
       [0.22330227],
       ...,
       [0.39045545],
       [0.4800283 ],
       [0.15766174]], dtype=float32)

#Results

In [57]:
for cell in np.nditer(y_pred, op_flags=['readwrite']):
    if cell[...] > 0.5:
      cell[...] = 1
    else:
      cell[...] = 0
y_pred

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [62]:
len(y_pred)

85065

In [70]:
len(test_dataset['n1'])

85065

In [72]:
test2_dataset = pd.read_csv('datathon_test.csv')
test2_dataset['label'] = y_pred
submission = test2_dataset[["id", "label"]]

submission.to_csv("predictions.csv", index = False)
#pd.to_csv("submission_1.csv", index=False)